# Getting Weather

## Loading Packages

In [1]:
import numpy as np
import pandas as pd
import glob
import plotly.express as px
import folium

import os
from pathlib import Path
from urllib.request import urlretrieve
from urllib.error import HTTPError, URLError
from zipfile import ZipFile

import requests

In [2]:
output_dir = "../data"

In [4]:
citibike_df = pd.read_csv(f"{output_dir}/JC/JC2025.csv", parse_dates=['started_at', 'ended_at'])

In [5]:
lat = 40.7178
lng = -74.0431

start_date = '2025-01-01'
end_date = '2025-12-31'

url = 'https://archive-api.open-meteo.com/v1/archive'

params = {
    'latitude': lat,
    'longitude': lng,
    "start_date": start_date,
    "end_date": end_date,
    "daily": [
        "temperature_2m_max",
        "temperature_2m_min",
        "temperature_2m_mean",
        "precipitation_sum",
        "rain_sum",
        "snowfall_sum",
        "wind_speed_10m_max"
    ],
    "timezone": "America/New_York"
    
}

response = requests.get(url, params=params)
response.raise_for_status()

In [6]:
data = response.json()

In [7]:
data['daily'].keys()

dict_keys(['time', 'temperature_2m_max', 'temperature_2m_min', 'temperature_2m_mean', 'precipitation_sum', 'rain_sum', 'snowfall_sum', 'wind_speed_10m_max'])

In [8]:
weather_data = pd.DataFrame(data['daily'])
weather_data.head()

,time,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max
0,2025-01-01,11.0,3.9,7.4,4.5,4.5,0.0,23.2
1,2025-01-02,5.4,0.3,2.6,0.0,0.0,0.0,25.1
2,2025-01-03,3.2,-1.9,0.4,0.0,0.0,0.0,17.1
3,2025-01-04,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1
4,2025-01-05,0.4,-3.6,-2.2,0.0,0.0,0.0,19.9

In [9]:
weather_data.rename(columns={'time':'date'},inplace=True)
weather_data.to_csv(f'{output_dir}/JC/jersey_weather_2025.csv', index=False)

In [10]:
weather_daily = pd.read_csv(f'{output_dir}/JC/jersey_weather_2025.csv', parse_dates=['date'])
weather_daily.info()

<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 365 non-null    datetime64[us]
 1   temperature_2m_max   365 non-null    float64
 2   temperature_2m_min   365 non-null    float64
 3   temperature_2m_mean  365 non-null    float64
 4   precipitation_sum    365 non-null    float64
 5   rain_sum             365 non-null    float64
 6   snowfall_sum         365 non-null    float64
 7   wind_speed_10m_max   365 non-null    float64
dtypes: datetime64[us](1), float64(7)
memory usage: 22.9 KB

In [11]:
weather_daily.head()

,date,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max
0,2025-01-01,11.0,3.9,7.4,4.5,4.5,0.0,23.2
1,2025-01-02,5.4,0.3,2.6,0.0,0.0,0.0,25.1
2,2025-01-03,3.2,-1.9,0.4,0.0,0.0,0.0,17.1
3,2025-01-04,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1
4,2025-01-05,0.4,-3.6,-2.2,0.0,0.0,0.0,19.9